### ISSUE TITLE
リンク集のリンク切れ

### ISSUE THREAD

**Issue by tatsuosakurai** [ppworks/koshikawa.jp#15]
http://www.koshikawa.jp/link.html の "えきから時刻表　大鳥居" がリンク切れしているようです
ekikara.jp はなくなっちゃった(?_?)みたいでした＞＜
https://tabiris.com/archives/ekikara/

**Comment by ppworks** [comment]
うおお

**Comment by ppworks** [comment]
> 結論を書くと、残念ながら、「えきから時刻表」に匹敵する時刻表検索サイトは、見つかりませんでした。

**Comment by ppworks** [comment]
リンク先候補: https://norikae.keikyu.co.jp/transit/norikae/T1?sf=%91%e5%92%b9%8b%8f
